#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Gridwolf appliance provisioning — converts a fresh Ubuntu 24.04 LTS VM
# into a self-contained Tenable-Core-style appliance:
#
#   * Gridwolf UI        → https://<host>:3000
#   * Gridwolf API       → https://<host>:8000
#   * Cockpit console    → https://<host>:9090   (full Linux web GUI)
#
# Idempotent: re-running upgrades Cockpit + the Gridwolf stack cleanly.
# Expected to be invoked by Packer during OVA build AND usable by an operator
# on any freshly-installed Ubuntu 24.04 LTS VM to produce the same result.
#
# Usage (manual):
#     sudo GRIDWOLF_ADMIN_PASSWORD='strong-pw' ./provision.sh
#
# Environment:
#     GRIDWOLF_ADMIN_USERNAME   default: admin
#     GRIDWOLF_ADMIN_EMAIL      default: admin@gridwolf.local
#     GRIDWOLF_ADMIN_PASSWORD   default: random — printed at end
#     GRIDWOLF_VERSION          default: latest (Docker Hub tag)
#     GRIDWOLF_BIND_ADDRESS     default: 0.0.0.0 (bind all interfaces)
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ---- argv / env ------------------------------------------------------------
: "${GRIDWOLF_ADMIN_USERNAME:=admin}"
: "${GRIDWOLF_ADMIN_EMAIL:=admin@gridwolf.local}"
: "${GRIDWOLF_ADMIN_PASSWORD:=}"
: "${GRIDWOLF_VERSION:=latest}"
: "${GRIDWOLF_BIND_ADDRESS:=0.0.0.0}"

INSTALL_ROOT=/opt/gridwolf
ENV_FILE="${INSTALL_ROOT}/.env"
COMPOSE_FILE="${INSTALL_ROOT}/docker-compose.yml"
COCKPIT_ASSETS_DIR=/usr/share/cockpit/gridwolf
MOTD_FILE=/etc/motd
LOG_TAG="[gridwolf-provision]"

log() { printf "%s %s\n" "$LOG_TAG" "$*"; }
die() { printf "%s ERROR: %s\n" "$LOG_TAG" "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "must run as root"

# ---- OS sanity --------------------------------------------------------------
. /etc/os-release
[[ "${ID}" == "ubuntu" ]] || die "this script targets Ubuntu 24.04 (got: ${ID})"
[[ "${VERSION_ID}" == "24.04" ]] || log "WARNING: tested on 24.04, running on ${VERSION_ID}"

# ---- package install --------------------------------------------------------
log "refreshing apt..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get install -y -q \
    ca-certificates curl gnupg lsb-release \
    ufw fail2ban unattended-upgrades \
    cockpit cockpit-podman cockpit-networkmanager cockpit-storaged \
    cockpit-packagekit cockpit-pcp cockpit-sosreport \
    jq python3-venv openssl

# Docker (official repo for a sane compose version)
if ! command -v docker >/dev/null 2>&1; then
    log "installing Docker from docker.com repo..."
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
         https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list
    apt-get update -q
    apt-get install -y -q docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi

systemctl enable --now docker

# ---- filesystem layout ------------------------------------------------------
log "laying out ${INSTALL_ROOT}..."
install -d -m 0755 -o root -g root "${INSTALL_ROOT}"
install -d -m 0750 "${INSTALL_ROOT}/data"
install -d -m 0750 "${INSTALL_ROOT}/reports"
install -d -m 0750 "${INSTALL_ROOT}/uploads"
install -d -m 0750 "${INSTALL_ROOT}/backups"

# ---- .env generation --------------------------------------------------------
if [[ ! -f "${ENV_FILE}" ]]; then
    log "generating ${ENV_FILE}..."

    SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_urlsafe(64))')

    if [[ -z "${GRIDWOLF_ADMIN_PASSWORD}" ]]; then
        GRIDWOLF_ADMIN_PASSWORD=$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))')
        PASSWORD_GENERATED=1
    else
        PASSWORD_GENERATED=0
    fi

    cat > "${ENV_FILE}" <<EOF
# Generated by gridwolf provision.sh — do not edit secrets by hand.
GRIDWOLF_SECRET_KEY=${SECRET_KEY}
GRIDWOLF_DEBUG=false
GRIDWOLF_DATABASE_URL=sqlite+aiosqlite:////app/data/gridwolf.db
GRIDWOLF_CORS_ORIGINS=["http://localhost:3000","https://localhost:3000"]
GRIDWOLF_ADMIN_USERNAME=${GRIDWOLF_ADMIN_USERNAME}
GRIDWOLF_ADMIN_EMAIL=${GRIDWOLF_ADMIN_EMAIL}
GRIDWOLF_ADMIN_PASSWORD=${GRIDWOLF_ADMIN_PASSWORD}
GRIDWOLF_IMAGE=gridwolf/backend:${GRIDWOLF_VERSION}
GRIDWOLF_FRONTEND_IMAGE=gridwolf/frontend:${GRIDWOLF_VERSION}
GRIDWOLF_BIND_ADDRESS=${GRIDWOLF_BIND_ADDRESS}
EOF
    chmod 0600 "${ENV_FILE}"

    if [[ "${PASSWORD_GENERATED}" == "1" ]]; then
        echo "${GRIDWOLF_ADMIN_PASSWORD}" > "${INSTALL_ROOT}/.admin-password"
        chmod 0600 "${INSTALL_ROOT}/.admin-password"
    fi
else
    log "${ENV_FILE} already exists — leaving secrets untouched"
fi

# ---- compose file (pinned to Docker Hub tags, no local build) --------------
log "writing ${COMPOSE_FILE}..."
cat > "${COMPOSE_FILE}" <<'EOF'
# Gridwolf appliance compose — pulls published images, no local build.
services:
  backend:
    image: ${GRIDWOLF_IMAGE}
    restart: unless-stopped
    env_file: .env
    environment:
      GRIDWOLF_UPLOAD_DIR: /app/uploads
      GRIDWOLF_REPORTS_DIR: /app/reports
    ports:
      - "${GRIDWOLF_BIND_ADDRESS}:8000:8000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  frontend:
    image: ${GRIDWOLF_FRONTEND_IMAGE}
    restart: unless-stopped
    ports:
      - "${GRIDWOLF_BIND_ADDRESS}:3000:80"
    depends_on:
      backend:
        condition: service_healthy
EOF

# ---- systemd unit so the stack comes up on boot ----------------------------
log "installing systemd unit..."
cat > /etc/systemd/system/gridwolf.service <<EOF
[Unit]
Description=Gridwolf ICS/SCADA security appliance
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${INSTALL_ROOT}
EnvironmentFile=${ENV_FILE}
ExecStartPre=/usr/bin/docker compose pull --quiet
ExecStart=/usr/bin/docker compose up -d --remove-orphans
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=600

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable gridwolf.service

# ---- Cockpit: enable + brand ------------------------------------------------
log "enabling Cockpit on :9090..."
systemctl enable --now cockpit.socket

# Custom Cockpit landing page with a big "Launch Gridwolf" tile
install -d -m 0755 "${COCKPIT_ASSETS_DIR}"
cat > "${COCKPIT_ASSETS_DIR}/manifest.json" <<'EOF'
{
  "version": 1,
  "name": "gridwolf",
  "menu": {
    "index": {
      "label": "Gridwolf",
      "order": 5,
      "docs": [
        { "label": "Gridwolf UI",  "url": "/gridwolf/launch.html" },
        { "label": "Operator Guide", "url": "https://github.com/valinorintelligence/Gridwolf/blob/main/deploy/ova/README.md" }
      ]
    }
  },
  "content-security-policy": "img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'"
}
EOF

cat > "${COCKPIT_ASSETS_DIR}/launch.html" <<'EOF'
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Gridwolf</title>
  <style>
    body { background:#060917; color:#f0f0ff; font-family:system-ui,sans-serif;
           display:flex; align-items:center; justify-content:center; min-height:100vh; margin:0; }
    .card { background:#0b1226; border:1px solid #1a1f3d; border-radius:16px;
            padding:40px; text-align:center; max-width:420px;
            box-shadow:0 10px 40px rgba(34,211,238,0.1); }
    h1 { margin:0 0 8px; background:linear-gradient(135deg,#22d3ee,#7c3aed);
         -webkit-background-clip:text; background-clip:text; color:transparent;
         font-size:32px; letter-spacing:2px; }
    p { color:#9ca3c7; margin:8px 0 28px; font-size:14px; line-height:1.6; }
    a.primary { display:inline-block; padding:12px 28px; border-radius:10px;
                background:linear-gradient(135deg,#22d3ee,#7c3aed); color:#fff;
                text-decoration:none; font-weight:600; letter-spacing:0.5px; }
    a.primary:hover { filter: brightness(1.1); }
    .ports { margin-top:24px; font-size:11px; color:#6b72a0;
             border-top:1px solid #1a1f3d; padding-top:16px; }
    code { background:#151937; padding:2px 6px; border-radius:4px; color:#22d3ee; }
  </style>
</head>
<body>
  <div class="card">
    <h1>GRIDWOLF</h1>
    <p>Passive ICS/SCADA network discovery &amp; vulnerability intelligence.</p>
    <a class="primary" id="launch" href="#">Open Gridwolf UI</a>
    <div class="ports">
      Gridwolf UI <code>:3000</code> &nbsp;·&nbsp;
      API <code>:8000</code> &nbsp;·&nbsp;
      Cockpit <code>:9090</code>
    </div>
  </div>
  <script>
    // Rewrite link to the appliance's actual hostname on whatever port
    // Cockpit was reached at — keeps the tile portable across IPs / DNS.
    document.getElementById('launch').href =
      location.protocol + '//' + location.hostname + ':3000/';
  </script>
</body>
</html>
EOF

# Cockpit session banner — shown on the login page
install -d -m 0755 /etc/issue.d
cat > /etc/cockpit/cockpit.conf <<EOF
[WebService]
LoginTitle = Gridwolf Appliance
LoginTo = false

[Session]
Banner = /etc/gridwolf/cockpit-banner.txt
EOF
install -d -m 0755 /etc/gridwolf
cat > /etc/gridwolf/cockpit-banner.txt <<'EOF'
┌──────────────────────────────────────────────────────────────┐
│  GRIDWOLF APPLIANCE — Linux management console (Cockpit)     │
│  For the Gridwolf product UI, connect to port 3000.          │
│  This console manages the HOST OS: storage, network,         │
│  services, logs, updates, terminal, SSH keys.                │
└──────────────────────────────────────────────────────────────┘
EOF

# ---- MOTD (SSH login banner) ----------------------------------------------
cat > "${MOTD_FILE}" <<EOF

  ╔═════════════════════════════════════════════════════════════╗
  ║                    GRIDWOLF APPLIANCE                       ║
  ╠═════════════════════════════════════════════════════════════╣
  ║   Gridwolf UI  :  https://$(hostname -I | awk '{print $1}'):3000
  ║   Cockpit      :  https://$(hostname -I | awk '{print $1}'):9090
  ║   API          :  https://$(hostname -I | awk '{print $1}'):8000
  ╚═════════════════════════════════════════════════════════════╝

  Service control:
      systemctl status  gridwolf
      systemctl restart gridwolf
      journalctl -u gridwolf -f

  Data volumes:
      ${INSTALL_ROOT}/data     — SQLite + session data
      ${INSTALL_ROOT}/reports  — generated assessment reports
      ${INSTALL_ROOT}/uploads  — inbound PCAPs / scans

EOF

# ---- firewall ---------------------------------------------------------------
log "configuring ufw..."
ufw --force reset >/dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp    comment 'SSH'
ufw allow 3000/tcp  comment 'Gridwolf UI'
ufw allow 8000/tcp  comment 'Gridwolf API'
ufw allow 9090/tcp  comment 'Cockpit'
ufw --force enable

# ---- unattended security upgrades -------------------------------------------
log "enabling unattended security upgrades..."
cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

# ---- pull & launch ----------------------------------------------------------
log "pulling gridwolf images (this may take a few minutes)..."
(cd "${INSTALL_ROOT}" && docker compose pull)

log "starting gridwolf service..."
systemctl start gridwolf.service

# ---- wait for health --------------------------------------------------------
log "waiting for Gridwolf health endpoint..."
for i in {1..30}; do
    if curl -sf http://localhost:8000/health >/dev/null 2>&1; then
        log "backend healthy"
        break
    fi
    sleep 2
    [[ $i -eq 30 ]] && die "backend did not come up — check: journalctl -u gridwolf"
done

# ---- summary ----------------------------------------------------------------
IP=$(hostname -I | awk '{print $1}')
cat <<EOF

─────────────────────────────────────────────────────────────
  Gridwolf appliance provisioned successfully.

  URLs:
    Gridwolf UI        https://${IP}:3000
    Gridwolf API       https://${IP}:8000/docs
    Cockpit console    https://${IP}:9090

  Admin username:  ${GRIDWOLF_ADMIN_USERNAME}
EOF

if [[ -f "${INSTALL_ROOT}/.admin-password" ]]; then
    cat <<EOF
  Admin password:  $(cat "${INSTALL_ROOT}/.admin-password")
  (also saved at ${INSTALL_ROOT}/.admin-password — rotate and delete)
EOF
fi

cat <<EOF
─────────────────────────────────────────────────────────────
EOF
