#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Gridwolf OVA build — Step 3: First-boot wizard + systemd services
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

INSTALL_DIR="/opt/gridwolf"

# ── gridwolf-setup  (runs ONCE on first boot, then disables itself) ───────────
cat > /usr/local/bin/gridwolf-setup <<'SETUP'
#!/usr/bin/env bash
# Gridwolf first-boot configuration wizard
set -euo pipefail

INSTALL_DIR="/opt/gridwolf"
ENV_FILE="${INSTALL_DIR}/.env"
DONE_FLAG="${INSTALL_DIR}/.setup-complete"

[[ -f "$DONE_FLAG" ]] && exit 0

clear
cat <<'BANNER'
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║        ██████╗ ██████╗ ██╗██████╗ ██╗    ██╗ ██████╗ ██╗   ║
║       ██╔════╝ ██╔══██╗██║██╔══██╗██║    ██║██╔═══██╗██║   ║
║       ██║  ███╗██████╔╝██║██║  ██║██║ █╗ ██║██║   ██║██║   ║
║       ██║   ██║██╔══██╗██║██║  ██║██║███╗██║██║   ██║██║   ║
║       ╚██████╔╝██║  ██║██║██████╔╝╚███╔███╔╝╚██████╔╝██║   ║
║        ╚═════╝ ╚═╝  ╚═╝╚═╝╚═════╝  ╚══╝╚══╝  ╚═════╝ ╚═╝   ║
║                                                              ║
║            ICS / OT Security Platform                        ║
║              First-Boot Configuration                        ║
╚══════════════════════════════════════════════════════════════╝
BANNER
echo

# Detect primary IP
DETECTED_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)
DETECTED_IP="${DETECTED_IP:-$(hostname -I | awk '{print $1}')}"

echo "  Detected IP address: ${DETECTED_IP}"
read -rp "  Confirm IP / hostname [${DETECTED_IP}]: " USER_IP
HOST="${USER_IP:-$DETECTED_IP}"

echo
read -rsp "  Set admin password (min 12 chars): " ADMIN_PASS
echo
read -rsp "  Confirm admin password: " ADMIN_PASS2
echo
if [[ "$ADMIN_PASS" != "$ADMIN_PASS2" ]]; then
  echo "  ✗ Passwords do not match. Reboot and try again." >&2
  exit 1
fi
if [[ ${#ADMIN_PASS} -lt 12 ]]; then
  echo "  ✗ Password must be at least 12 characters." >&2
  exit 1
fi

echo
echo "  Generating secrets..."

SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")
POSTGRES_PASS=$(openssl rand -hex 32)

cat > "$ENV_FILE" <<EOF
# Gridwolf runtime environment — generated by first-boot wizard
# DO NOT share this file.

GRIDWOLF_SECRET_KEY=${SECRET_KEY}
GRIDWOLF_DEBUG=false
POSTGRES_PASSWORD=${POSTGRES_PASS}
GRIDWOLF_CORS_ORIGINS=["http://${HOST}","https://${HOST}"]
GRIDWOLF_UPLOAD_DIR=/data/uploads
GRIDWOLF_REPORTS_DIR=/data/reports
EOF

chmod 600 "$ENV_FILE"
chown gridwolf:gridwolf "$ENV_FILE"

echo "  Starting services..."
cd "$INSTALL_DIR"
docker compose --env-file "$ENV_FILE" up -d

# Wait for backend health (up to 80s)
ADMIN_PASSWORD_SHOWN=""
for i in $(seq 1 40); do
  if curl -sf "http://localhost:8000/health" 2>/dev/null | grep -q '"status":"ok"'; then
    # Scrape the auto-generated admin password from backend startup logs
    ADMIN_PASSWORD_SHOWN=$(docker compose -f "$INSTALL_DIR/docker-compose.yml" \
      --env-file "$ENV_FILE" logs backend 2>/dev/null \
      | grep -A1 "Password " | grep -v "Password" | tr -d ' \r' | head -1 || true)
    break
  fi
  sleep 2
done

# Mark setup as complete
touch "$DONE_FLAG"

# Disable this service so it never runs again
systemctl disable gridwolf-setup.service 2>/dev/null || true

SHOW_PASS="${ADMIN_PASSWORD_SHOWN:-check container logs: docker compose logs backend}"
clear
cat <<EOF

  ╔══════════════════════════════════════════════════════════════╗
  ║  ✓  Gridwolf is running!                                    ║
  ║                                                              ║
  ║  Open your browser:  http://${HOST}
  ║  API docs:           http://${HOST}/api/docs
  ║                                                              ║
  ║  First-run admin credentials:                                ║
  ║    Username:  admin                                          ║
  ║    Password:  ${SHOW_PASS}
  ║                                                              ║
  ║  Change this password immediately after first login.         ║
  ╚══════════════════════════════════════════════════════════════╝

EOF
SETUP

chmod +x /usr/local/bin/gridwolf-setup

# ── gridwolf-setup.service  ───────────────────────────────────────────────────
cat > /etc/systemd/system/gridwolf-setup.service <<'UNIT'
[Unit]
Description=Gridwolf First-Boot Setup Wizard
After=network-online.target docker.service
Wants=network-online.target
ConditionPathExists=!/opt/gridwolf/.setup-complete

[Service]
Type=oneshot
ExecStart=/usr/local/bin/gridwolf-setup
StandardInput=tty
TTYPath=/dev/tty1
StandardOutput=tty
StandardError=tty
RemainAfterExit=yes
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
UNIT

# ── gridwolf.service  (starts after setup, restarts containers on boot) ───────
cat > /etc/systemd/system/gridwolf.service <<'UNIT'
[Unit]
Description=Gridwolf ICS Security Platform
After=network-online.target docker.service gridwolf-setup.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/gridwolf
EnvironmentFile=/opt/gridwolf/.env
ExecStart=docker compose up -d
ExecStop=docker compose down
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable gridwolf-setup.service
systemctl enable gridwolf.service

echo "[gridwolf] Systemd services installed and enabled."
