{{- if and .Values.redis.enabled (not .Values.redis.host) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gridwolf.fullname" . }}-redis
  labels:
    {{- include "gridwolf.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "gridwolf.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "gridwolf.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          args: ["--appendonly", "yes"]
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 2
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gridwolf.fullname" . }}-redis
  labels:
    {{- include "gridwolf.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      name: redis
  selector:
    {{- include "gridwolf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
